# Generated by Django 5.2.4 on 2025-07-10 07:16

import cartelera.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0002_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(validators=[cartelera.validators.validar_mayor]),
        ),
    ]
