# Generated by Django 5.2.4 on 2025-07-12 07:07

import cartelera.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0003_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cartelera.genero'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200, validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco]),
        ),
    ]
