# Generated by Django 5.2.4 on 2025-07-12 16:06

import cartelera.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0004_alter_genero_nombre_alter_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2, unique=True, validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco])),
                ('capacidad', models.IntegerField(validators=[cartelera.validators.validar_mayor])),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_funcion', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=4)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[cartelera.validators.validar_mayor])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cartelera.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cartelera.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.IntegerField(blank=True, null=True, validators=[cartelera.validators.validar_mayor])),
                ('email', models.CharField(blank=True, null=True, validators=[cartelera.validators.validar_email])),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('fecha_funcion', models.DateField()),
                ('cantidad_boletos', models.IntegerField(validators=[cartelera.validators.validar_mayor])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[cartelera.validators.validar_mayor])),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cartelera.funcion')),
            ],
        ),
    ]
