# Generated by Django 5.2.4 on 2025-07-12 19:04

import cartelera.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0005_sala_funcion_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.IntegerField(unique=True, validators=[cartelera.validators.validar_mayor]),
        ),
    ]
