# Generated by Django 5.2.4 on 2025-07-12 19:14

import cartelera.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0007_remove_sala_nombre_sala_nro_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nro_sala',
            field=models.CharField(max_length=10, unique=True, validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco]),
        ),
    ]
