# Generated by Django 5.2.4 on 2025-07-13 03:55

import cartelera.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0010_alter_sala_nro_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.genero', validators=[cartelera.validators.validar_vacio, cartelera.validators.validar_espacio_en_blanco]),
        ),
    ]
