# Generated by Django 5.2.4 on 2025-07-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0011_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.sala'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.funcion'),
        ),
    ]
