# Generated by Django 5.2.4 on 2025-07-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0012_alter_funcion_pelicula_alter_funcion_sala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='hora',
            field=models.TimeField(choices=[('10:00', 'Diez'), ('12:00', 'Doce'), ('14:00', 'Catorce'), ('16:00', 'Dieciseis'), ('18:00', 'Dieciocho'), ('20:00', 'Veinte'), ('22:00', 'Veintidos')], default='10:00'),
        ),
    ]
