# Generated by Django 5.2.4 on 2025-07-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0014_funcion_funcion_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='hora',
            field=models.TimeField(choices=[('10:00:00', 'Diez'), ('12:00:00', 'Doce'), ('14:00:00', 'Catorce'), ('16:00:00', 'Dieciseis'), ('18:00:00', 'Dieciocho'), ('20:00:00', 'Veinte'), ('22:00:00', 'Veintidos')], default='10:00:00'),
        ),
    ]
