# Generated by Django 5.2.4 on 2025-07-13 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0015_alter_funcion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='hora',
            field=models.TimeField(choices=[(datetime.time(0, 0), 'Midnight'), (datetime.time(10, 0), '9:00 AM'), (datetime.time(12, 0), 'Noon'), (datetime.time(17, 0), '5:00 PM'), (datetime.time(22, 0), '10:00 PM')]),
        ),
    ]
