# Generated by Django 5.2.4 on 2025-07-13 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0016_alter_funcion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='hora',
            field=models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(10, 0), '10:00'), (datetime.time(12, 0), '12:00'), (datetime.time(14, 0), '14:00'), (datetime.time(16, 0), '16:00'), (datetime.time(18, 0), '18:00'), (datetime.time(20, 0), '20:00'), (datetime.time(22, 0), '22:00')]),
        ),
    ]
