# Generated by Django 5.2.4 on 2025-07-13 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0017_alter_funcion_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_retiro',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
