# Generated by Django 5.2.4 on 2025-07-13 07:59

import cartelera.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0018_remove_funcion_fecha_fin_remove_funcion_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.genero', validators=[cartelera.validators.validar_mayor]),
        ),
    ]
