# Generated by Django 5.2.4 on 2025-07-13 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0019_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.genero'),
        ),
    ]
