# Generated by Django 5.2.4 on 2025-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0020_alter_pelicula_genero'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='funcion',
            name='funcion_unica',
            constraint=models.UniqueConstraint(fields=('sala_id', 'pelicula_id', 'hora'), name='funcion_unica', violation_error_message='Ya existe una funcion con la misma pelicula, sala y hora.'),
        ),
    ]
