# Generated by Django 5.2.4 on 2025-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0022_remove_funcion_funcion_unica_funcion_funcion_unica'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcion',
            name='funcion_unica',
        ),
        migrations.AddConstraint(
            model_name='funcion',
            constraint=models.UniqueConstraint(fields=('sala_id', 'pelicula_id', 'hora'), name='funcion_unica', violation_error_message='Ya existe una funcion con la misma pelicula, sala y hora.'),
        ),
    ]
