# Generated by Django 5.2.4 on 2025-07-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0024_remove_funcion_funcion_unica_funcion_funcion_unica'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='funcion',
            name='funcion_unica',
        ),
    ]
