# Generated by Django 5.2.4 on 2025-07-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0025_remove_funcion_funcion_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
